project:
  type: website

website:
  title: "First-Website by Terence"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - sidebar:sources
      - sidebar:interactive

  sidebar:
    - id: sources
      title: "Sources"
      style: "floating"
      background: "#ffffff"
      collapse-level: 2
      contents:
        - source-1.qmd
        - source-2.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



